# XTerm's default colors

# Default colors
[colors.primary]
background = '#20202a'
foreground = '#A0ABC4'

# Normal colors
[colors.normal]
black   = '#1a1a24'
red     = '#e06b6b'
green   = '#7d9685'
yellow  = '#c8cca7'
blue    = '#8BD0EC'
magenta = '#F093D8'
cyan    = '#b8dceb'
white   = '#cccbd9'

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
opacity = 1

[window.padding]
x = 10
y = 10
